---
# Install Postgres


- name: Instal Postgres 10
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: present

- name: Install Postgres Client Packages
  yum:
    name: postgresql10
    state: latest

- name: Install Postgres Server Packages
  yum:
    name: postgresql10-server
    state: latest

- name: Init Postgres DB
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: enable and start postgres
  systemd:
    name: postgresql-10
    state: started
    enabled: True
