---
# Install oracle java

- name: Create general download folder
  file:
    path: "{{ downloads_path }}"
    state: directory

- name: Download Oracle Java 8 repo script
  get_url:
    url: "{{ oracle_java_8_installer }}"
    dest: "{{ downloads_path }}"
    headers: "Cookie:oraclelicense=accept-securebackup-cookie"
    validate_certs: no

- name: Install Oracle Java 8
  yum:
    name: "{{ downloads_path }}/{{ oracle_java_8_rpm }}"
    state: present

- name: Delete Oracle Java download
  file:
    name: "{{ downloads_path }}/{{ oracle_java_8_rpm }}"
    state: absent
